### ISSUE TITLE
[HELP] how to use it?

### ISSUE THREAD

**Issue by snapboss** [0xXA/snapchat-emulator-bypass#1]
Hey, does this work for android emulators on PC (Bluestacks/LD player/Nox/Memu) 
Is root needed? 
Any starting point on how to use it? Thanks 
Edit: managed to push the files but the python script gives errors.
Snapchat doesn't login or display anything trying to login after pushing the libs. Is it patched already or the python script needs to run too so it can work?

**Comment by dreamyeye84** [comment]
You not knowing how to use this isn't very 'snapboss' of you is it

**Comment by snapboss** [comment]
> You not knowing how to use this isn't very 'snapboss' of you is it

Maybe "snapboss" is because I run million sub accounts, modding android app & android system has nothing to do with it :)
Anyway I managed to run everything :)
